---
- name: Install and configure Nginx on EC2
  hosts: all
  become: yes
  vars_files:
    - secrets.yml

  vars:
    html_content: |
      <html>
      <head><title>Welcome to My EC2!</title></head>
      <body style="background-color:#111; color:#eee; text-align:center; padding-top:10%;">
          <h1>Hello from Borham 🚀</h1>
          <p>Deployed via Dynamic Inventory on {{ ansible_hostname }}</p>
      </body>
      </html>

  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Update Nginx default HTML page
      ansible.builtin.copy:
        content: "{{ html_content }}"
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
