---
- name: Configure Nginx Web Server
  hosts: Nginx-server
  become: yes   # run as root (using sudo)

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        content: |
          <html>
          <head><title>Ansible Web Server</title></head>
          <body style="background-color:#1e1e2f; color:#fff; font-family:sans-serif;">
          <h1>Hello there its Borham</h1>
          <h2>Welcome from Nginx</h2>
          <p>This page was automatically configured using Ansible.</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
